export default {
  SET_PRODUCTS: "@/PRODUCTS/SET_PRODUCTS",
  ADD_FAVORITE: "@/FAVORITE/ADD_FAVORITE",
  DELETE_FAVORITE: "@/FAVORITE/DELETE_FAVORITE",
  DROPDOWN_VISIBLE: "@/DROPDOWN/DROPDOWN_VISIBLE",
};
